---
title: "snowdepth for stationdata only"
author: "Schimpfle, Wiech"
date: "2024-06-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
# import libraies
library("stars")
library("ggplot2")
library("dplyr")
library("lubridate")

library("zoo")
library("colorspace")
library("mgcv")
library("raster")
```


```{r}
# set working directory
#setwd("C:/Users/andre/OneDrive/Dokumente/UNI/Master_Semester_2/Geostatistics/FinalProject")
setwd("/Users/sschimpfle/Atmospärenwissenschaften/Geostatistic/Final_Project/FinalProjectGeostatistic")
```

### Get political boundary data (GADM)

```{r}
# Processing GADM data
autBoundaries <- read_sf("gadm41_AUT_1.json")
plot(st_geometry(autBoundaries)) # plot view base R
ggplot() + geom_sf(data = autBoundaries, fill = "lightblue") # plot in "tidyverse"
```

```{r}
#To extract a state, e.g. Tirol, and:
tirol <- subset(autBoundaries, NAME_1 == "Tirol")
# plot tirol
plot(st_geometry(tirol)) # plot view base R
ggplot() + geom_sf(data = tirol, fill = "lightblue") # plot in "tidyverse"
```

### Get SRTM digital elevation model data (DEM)
```{r}
# Processing SRTM Data
# Listing all unzipped srtm_*.tif files
files <- list.files()
files <- files[grepl("srtm_.*.tif$", files)]
print(files)

tmp <- lapply(files, read_stars)

dem <- do.call(st_mosaic, tmp)
st_crs(dem) <- st_crs(4326) # Adding lonlat coordinate reference
plot(dem)
```

After we spent quite some time to download the data correctly and to create a file with which you can edit the Dyad task.

### Read in the data
```{r}
filename <- "snowdepthdata.rds"
df <-readRDS(filename)
head(df)
```

### Further data prep
```{r}
colnames(df)[which(colnames(df) == "latitude")] <- "lon" 
colnames(df)[which(colnames(df) == "longitude")] <- "lat"
colnames(df)[which(colnames(df) == "station_altitude")] <- "alt"
df <- subset(df, select = -c(station_number))

# Define the location for the tensor spline (47.6 N, 10 E)
reference_lat <- 47.6
reference_lon <- 10.0

df <- df %>%
  mutate(
    lat_dist_km = (lat - reference_lat) * (pi / 180) * 6371,
    lon_dist_km = (lon - reference_lon) * (pi / 180) * 6371 * cos(reference_lat * pi / 180)
  )


head(df)
```
**Extract the names of all stations**
```{r}
# Extract the names of all stations
stations <- unique(df$station_name)
stations
```
**Add day of year yday to df**

```{r}
df$yday <- as.POSIXlt(df$date)$yday
```

```{r}
SnowModellsimpl <- gam(mean_snow_depth ~ s(alt, k = 5, bs = "cr") +
                    s(lat, lon, bs =("tp"), k = 5), data = df)


summary(SnowModellsimpl)
par(mfrow = c(1,2))
plot.gam(SnowModellsimpl)
```

```{r}
SnowModell <- gam(mean_snow_depth ~ s(alt, k = 5, bs = "cr") +
                    s(lat, lon, bs = "tp") +
                    ti(lat_dist_km, lon_dist_km, bs = c("tp","tp"), k = c(20,20)), data = df)


summary(SnowModell)
par(mfrow = c(1,2))
plot.gam(SnowModell)
```
```{r}
SnowModell_rad <- gam(mean_snow_depth ~ s(alt, k = 5, bs = "cr") +
                    s(lat, lon, bs = "tp") +
                    te(lat_dist_km, lon_dist_km, bs = "tp") +
                    s(globrad, k=5 ,bs = "cr"),
                  data = df)
summary(SnowModell_rad)
par(mfrow = c(2,2))
plot.gam(SnowModell_rad)
```
```{r}
dem <- readRDS("dem.rds")
tirol <- readRDS("tirol.gadm.rds")
```

```{r}
plot(dem, col = gray.colors(51))
plot(tirol, col = gray.colors(51))
```

```{r}
dem <- crop(dem, extent(tirol))
sp <- SpatialPoints(coordinates(dem), proj4string = crs(tirol))
take <- which(!is.na(over(sp, tirol)))
values(dem)[!take] <- NA
newdata <- as.data.frame(coordinates(dem))
names(newdata) <- c("lon","lat")
newdata$alt <- values(dem)
newdata <- newdata[take, ]
newdata <- newdata %>%
  mutate(
    lat_dist_km = (lat - reference_lat) * (pi / 180) * 6371,
    lon_dist_km = (lon - reference_lon) * (pi / 180) * 6371 * cos(reference_lat * pi / 180)
  )
#also calculate the long and lateral distance 
head(newdata)
```

```{r}
date <- as.POSIXlt("2019-12-01")
newdata$yday <- date$yday
Smodelsimpl <- predict(SnowModellsimpl, newdata = newdata)
```

```{r}
res <- dem
values(res) <- NA #initialize
res <- stack(res)
names(res) <- c("snowdepth")

# Then store the estimates (predictions)
values(res$snowdepth)[take] <- Smodelsimpl
```

```{r}
plot(res$snowdepth, col = diverge_hcl(51, h = c(260, 305),power = 1), main = sprintf("Daily mean temperature simple model %s", strftime(date, "%b %d")))
```
### Difference for 24h and 48 h
```{r}
date <- as.POSIXlt("2019-12-02")
newdata$yday <- date$yday
Smodelsimpl24 <- predict(SnowModellsimpl, newdata = newdata)
```

```{r}
res <- dem
values(res) <- NA #initialize
res <- stack(res)
names(res) <- c("snowdepth24")

# Then store the estimates (predictions)
values(res$snowdepth24)[take] <- Smodelsimpl24
```

```{r}
plot(res$snowdepth24 - res$snowdepth, col = diverge_hcl(51, h = c(260, 305),power = 1), main = sprintf("Daily mean temperature simple model %s", strftime(date, "%b %d")))
```
